#!/usr/bin/env bash
# install-cli-wrapper.sh — install a host-side openclaw CLI wrapper for Docker Compose deployments
#
# Creates ~/.local/bin/openclaw that routes:
#   openclaw gateway restart/start/stop → docker compose (Compose manages gateway lifecycle)
#   everything else                      → docker exec CLI_CONTAINER node dist/index.js
#
# Also writes ~/.openclaw/ops-config.sh so all openclaw-ops scripts pick up the
# correct stack dir and container names automatically (sourced by lib.sh).
#
# Usage:
#   bash scripts/install-cli-wrapper.sh
#   bash scripts/install-cli-wrapper.sh \
#       --stack-dir /srv/openclaw/openclaw \
#       --gateway-container openclaw-openclaw-gateway-1 \
#       --cli-container openclaw-openclaw-cli-1

set -euo pipefail

STACK_DIR="/srv/openclaw/openclaw"
GATEWAY_CONTAINER="openclaw-openclaw-gateway-1"
CLI_CONTAINER="openclaw-openclaw-cli-1"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stack-dir)         STACK_DIR="${2:-}";          shift 2 ;;
    --gateway-container) GATEWAY_CONTAINER="${2:-}";  shift 2 ;;
    --cli-container)     CLI_CONTAINER="${2:-}";      shift 2 ;;
    -h|--help)
      sed -n '2,12p' "${BASH_SOURCE[0]}"
      exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

WRAPPER="$HOME/.local/bin/openclaw"
OPS_CONFIG="$HOME/.openclaw/ops-config.sh"

mkdir -p "$(dirname "$WRAPPER")" "$(dirname "$OPS_CONFIG")"

# Write ops-config.sh — sourced by lib.sh so all scripts pick up these values.
cat > "$OPS_CONFIG" <<EOF
export OPENCLAW_STACK_DIR="${STACK_DIR}"
export OPENCLAW_GATEWAY_CONTAINER="${GATEWAY_CONTAINER}"
export OPENCLAW_CLI_CONTAINER="${CLI_CONTAINER}"
EOF
echo "Written: $OPS_CONFIG"

# Write the openclaw host wrapper.
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# openclaw host wrapper — generated by install-cli-wrapper.sh
# Routes gateway lifecycle commands to docker compose; everything else to docker exec.
set -euo pipefail

_STACK_DIR="${STACK_DIR}"
_CLI_CONTAINER="${CLI_CONTAINER}"

case "\${1:-}" in
  gateway)
    case "\${2:-}" in
      restart)
        exec docker compose -C "\$_STACK_DIR" restart openclaw-gateway ;;
      start)
        exec docker compose -C "\$_STACK_DIR" up -d openclaw-gateway ;;
      stop)
        exec docker compose -C "\$_STACK_DIR" stop openclaw-gateway ;;
      *)
        if [[ -t 0 && -t 1 ]]; then
          exec docker exec -it "\$_CLI_CONTAINER" node dist/index.js "\$@"
        else
          exec docker exec -i "\$_CLI_CONTAINER" node dist/index.js "\$@"
        fi ;;
    esac ;;
  *)
    if [[ -t 0 && -t 1 ]]; then
      exec docker exec -it "\$_CLI_CONTAINER" node dist/index.js "\$@"
    else
      exec docker exec -i "\$_CLI_CONTAINER" node dist/index.js "\$@"
    fi ;;
esac
EOF
chmod +x "$WRAPPER"
echo "Written: $WRAPPER"

# Remind about PATH if needed.
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$HOME/.local/bin"; then
  echo ""
  echo "Note: ~/.local/bin is not in your PATH."
  echo "  Add to ~/.bashrc:  export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo "  Then:              source ~/.bashrc"
fi

echo ""
echo "Done. Test with: openclaw --version"
